<a href="https://colab.research.google.com/github/PedroMatumoto/AI_Notebooks/blob/main/groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="ITM">
</head>

<img src="https://maua.br/images/selo-60-anos-maua.svg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->

In [1]:
import pandas as pd
import numpy as np

## **CASE Tips**

# Q1.

Considere a base de dados [`tips`](https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/tips.csv). Considerando somente os finais de semana, quem tem média de participantes na mesa maior, fumantes ou não fumantes? **`[NoGroup | GroupBy]`**

In [30]:
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/tips.csv')
df_finais_de_semana = df[df['day'].isin(['Sat', 'Sun'])]
df_finais_de_semana.groupby('smoker')['size'].mean()

smoker
No     2.764706
Yes    2.508197
Name: size, dtype: float64

## **CASE Insurance**

Acesse a base de dados [`insurance`](https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/insurance.csv) para as questões a seguir.

In [3]:
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Q2.

Qual percentual de homens e mulheres assegurados na base? **`[NoGroup | GroupBy]`**

In [8]:
print(len(df[df['sex'] == 'male'])/len(df))
print(len(df[df['sex'] == 'female'])/len(df))

df.groupby('sex').size()/len(df)

0.5052316890881914
0.4947683109118087

sex
female    0.494768
male      0.505232
dtype: float64

# Q3.

Qual o total do valor de seguro pago por homens e mulheres segurados na base? **`[NoGroup | GroupBy]`**

In [9]:
df.groupby('sex').charges.sum()

sex
female    8.321061e+06
male      9.434764e+06
Name: charges, dtype: float64

# Q4.

Qual o percentual de valor de seguros pagos por homens e mulheres segurados na base? **`[NoGroup | GroupBy]`**

In [10]:
df.groupby('sex').charges.sum()/df.charges.sum()

sex
female    0.468638
male      0.531362
Name: charges, dtype: float64

# Q5.

Não fumantes apresentam em média mais filhos? **`[NoGroup | GroupBy]`**

In [11]:
df.groupby('smoker').children.mean()

smoker
no     1.090226
yes    1.113139
Name: children, dtype: float64

# Q6.

Qual a média e maior de idade dentre os segurados homem, das regiões northwest ou northeast? **`[NoGroup | GroupBy]`**

In [12]:
df.groupby(['region','sex']).agg({'age':['mean','max']})

                        age
                       mean max
region    sex
northeast female  39.639752  64
          male    38.901840  64
northwest female  39.591463  64
          male    38.795031  64
southeast female  39.108571  64
          male    38.783069  64
southwest female  39.703704  64
          male    39.208589  64



## **CASE European Energy**

Qual o tipo de Energia mais produzido na Europa? O uso de fontes renováveis já é significativo?

<br>

<img src="https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" width=300, align="left">

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


[European Energy link](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-08-04/readme.md)

Explore aqui como é a produção de Energia na Europa empregando a base de dados [`energy_types`](https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/energy_types.csv). Você pode achar útil fazer uma exploração inicial dos dados antes de começar.

In [13]:
import pandas as pd
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/energy_types.csv')

df.head()

,country,country_name,type,level,2016,2017,2018
0,BE,Belgium,Conventional thermal,Level 1,30728.0,31316.0,30092.635
1,BE,Belgium,Nuclear,Level 1,41430.0,40128.5,26995.628
2,BE,Belgium,Hydro,Level 1,1476.0,1360.9,1239.248
3,BE,Belgium,Pumped hydro power,Level 2,1110.0,1093.2,983.190
4,BE,Belgium,Wind,Level 1,5340.0,6387.9,7177.346

# Q7.

Quantos tipos de energia e países diferentes há na base? **`[NoGroup | GroupBy]`**

country  type
AL       Conventional thermal    1
         Geothermal              1
         Hydro                   1
         Nuclear                 1
         Other                   1
                                ..
UK       Nuclear                 1
         Other                   1
         Pumped hydro power      1
         Solar                   1
         Wind                    1
Length: 296, dtype: int64

KeyError: 'energy_type'

In [ ]:
# prompt: Quantos tipos de energia e países diferentes há na base usando groupby

print(f"Tipos de energia: {df['energy_type'].nunique()}")
print(f"Países diferentes: {df['country'].nunique()}")

# Q8.

Qual o percentual de energia nuclear produzido na Europa no ano de 2018?

# Q9.

Qual o percentual de energia nuclear produzido na França no ano de 2018?

# Q10.

Qual o percentual de energias limpas produzida na Europa no ano de 2018? **`[NoGroup | GroupBy]`**

*Energias limpas somente Hidroelétrica, Eólica, Solar e Geotérmica.*

# Q11.

Considerando os anos de 2016, 2017 e 2018, a produção de energias limpas tem aumentado na Europa? Verifique em termos absolutos e percentuais.

*Energias limpas somente Hidroelétrica, Eólica, Solar e Geotérmica.*